server:
  port: 8081

spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:postgresql://postgres:5432/swiftpay
    username: swiftpay
    password: swiftpay
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      leak-detection-threshold: 20000
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: ledger-processor-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 500
      properties:
        fetch.min.bytes: 50000
        spring.json.trusted.packages: "com.swiftpay.shared.event"
        spring.json.value.default.type: "com.swiftpay.shared.event.PaymentInitiatedEvent"
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

swiftpay:
  kafka:
    topics:
      payment-initiated: swiftpay.payment.initiated
      payment-result: swiftpay.payment.result
